export const teamRoosters = [
  {
    teamName: 'Fox Gaming',
    slug: 'fox-gaming',
    players: [
      {
        name: 'Karlo Kovačić',
        nationality: 'Croatia',
        flagUrl: 'https://liquipedia.net/commons/images/c/c6/Hr_hd.png',
        summonerName: 'Falleo',
        role: 'top',
      },
      {
        name: 'Meho Wissam',
        nationality: 'Lebanon',
        flagUrl: 'https://liquipedia.net/commons/images/d/de/Lb_hd.png',
        summonerName: 'Porcupine',
        role: 'jungle',
      },
      {
        name: 'Saif Alshahrani',
        nationality: 'Saudi Arabia',
        flagUrl: 'https://liquipedia.net/commons/images/d/d6/Sa_hd.png',
        summonerName: 'Yoichi',
        role: 'mid',
      },
      {
        name: 'Yevhen Zavalnyi',
        nationality: 'Ukraine',
        flagUrl: 'https://liquipedia.net/commons/images/b/bb/Ua_hd.png',
        summonerName: 'Mytant',
        role: 'bot',
      },
      {
        name: 'Mehdi Ghalimi',
        nationality: 'Morocco',
        flagUrl: 'https://liquipedia.net/commons/images/8/81/Ma_hd.png',
        summonerName: 'Nova',
        role: 'support',
      },
    ],
  },
  {
    teamName: 'Geekay Esports',
    slug: 'geekay-esports',
    players: [
      {
        name: 'Max Günther',
        nationality: 'Germany',
        flagUrl: 'https://liquipedia.net/commons/images/0/0c/De_hd.png',
        summonerName: 'Satorius',
        role: 'top',
      },
      {
        name: 'Anton Andersson',
        nationality: 'Sweden',
        flagUrl: 'https://liquipedia.net/commons/images/0/02/Se_hd.png',
        summonerName: 'Viking',
        role: 'jungle',
      },
      {
        name: 'Ahmad Charif',
        nationality: 'Lebanon',
        flagUrl: 'https://liquipedia.net/commons/images/d/de/Lb_hd.png',
        summonerName: 'Giyuu',
        role: 'mid',
      },
      {
        name: 'Khalil Sahraoui',
        nationality: 'Algeria',
        flagUrl: 'https://liquipedia.net/commons/images/1/1d/Dz_hd.png',
        summonerName: 'Rin',
        role: 'bot',
      },
      {
        name: 'Waleed Mohammad',
        nationality: 'Jordan',
        flagUrl: 'https://liquipedia.net/commons/images/1/10/Jo_hd.png',
        summonerName: 'DeKap',
        role: 'support',
      },
    ],
  },
  {
    teamName: 'GNG Esports',
    slug: 'gng-esports',
    players: [
      {
        name: 'Muhammed Fathy',
        nationality: 'Egypt',
        flagUrl: 'https://liquipedia.net/commons/images/d/d0/Eg_hd.png',
        summonerName: 'Murph',
        role: 'top',
      },
      {
        name: 'Attia Haithem',
        nationality: 'Tunisia',
        flagUrl: 'https://liquipedia.net/commons/images/3/31/Tn_hd.png',
        summonerName: 'Dean',
        role: 'jungle',
      },
      {
        name: 'Koussay Soltani',
        nationality: 'Tunisia',
        flagUrl: 'https://liquipedia.net/commons/images/3/31/Tn_hd.png',
        summonerName: 'Koussay',
        role: 'mid',
      },
      {
        name: 'Juhyeong Kim',
        nationality: 'Korea',
        flagUrl: 'https://liquipedia.net/commons/images/8/8c/Kr_hd.png',
        summonerName: 'Shark',
        role: 'bot',
      },
      {
        name: 'Yusin Gwak',
        nationality: 'Korea',
        flagUrl: 'https://liquipedia.net/commons/images/8/8c/Kr_hd.png',
        summonerName: 'Yusin',
        role: 'support',
      },
    ],
  },

  {
    teamName: 'Nigma Galaxy',
    slug: 'nigma-galaxy',
    players: [
      {
        name: 'Mohammed Sayed',
        nationality: 'Egypt',
        flagUrl: 'https://liquipedia.net/commons/images/d/d0/Eg_hd.png',
        summonerName: 'Boda',
        role: 'top',
      },
      {
        name: 'Jackson Pavone',
        nationality: 'Australia',
        flagUrl: 'https://liquipedia.net/commons/images/a/a3/Au_hd.png',
        summonerName: 'Pabu',
        role: 'jungle',
      },
      {
        name: 'Sven Vidovic',
        nationality: 'Croatia',
        flagUrl: 'https://liquipedia.net/commons/images/c/c6/Hr_hd.png',
        summonerName: 'Dehaste',
        role: 'mid',
      },
      {
        name: 'Khalifa Al-Dhaheri',
        nationality: 'United Arab Emirates',
        flagUrl: 'https://liquipedia.net/commons/images/b/bc/Ae_hd.png',
        summonerName: 'Rust',
        role: 'bot',
      },
      {
        name: 'Mohammad Al Khalailah',
        nationality: 'Jordan',
        flagUrl: 'https://liquipedia.net/commons/images/1/10/Jo_hd.png',
        summonerName: 'KlownZ',
        role: 'support',
      },
    ],
  },
  {
    teamName: 'Triple Esports',
    slug: 'triple-esports',
    players: [
      {
        name: 'Kallon Ram',
        nationality: 'United Kingdom',
        flagUrl: 'https://liquipedia.net/commons/images/5/5e/Gb_hd.png',
        summonerName: 'Kerberos',
        role: 'top',
      },
      {
        name: 'Safwan Eslam',
        nationality: 'Palestine',
        flagUrl: 'https://liquipedia.net/commons/images/8/88/Ps_hd.png',
        summonerName: 'Kudy',
        role: 'jungle',
      },
      {
        name: 'Fares Bouhajja',
        nationality: 'Tunisia',
        flagUrl: 'https://liquipedia.net/commons/images/3/31/Tn_hd.png',
        summonerName: 'Wicked',
        role: 'mid',
      },
      {
        name: 'Ala Jalleb',
        nationality: 'Tunisia',
        flagUrl: 'https://liquipedia.net/commons/images/3/31/Tn_hd.png',
        summonerName: 'Jalleba',
        role: 'bot',
      },
      {
        name: 'Taieb Kraiem',
        nationality: 'Tunisia',
        flagUrl: 'https://liquipedia.net/commons/images/3/31/Tn_hd.png',
        summonerName: 'Insane',
        role: 'support',
      },
    ],
  },
  {
    teamName: 'RAAD',
    slug: 'raad',
    players: [
      {
        name: 'Maged Marwan',
        nationality: 'Egypt',
        flagUrl: 'https://liquipedia.net/commons/images/d/d0/Eg_hd.png',
        summonerName: 'Maged',
        role: 'top',
      },
      {
        name: 'Andreas Aarlund',
        nationality: 'Denmark',
        flagUrl: 'https://liquipedia.net/commons/images/7/7d/Dk_hd.png',
        summonerName: 'Skude',
        role: 'jungle',
      },
      {
        name: 'Oussama Cherradi',
        nationality: 'Morocco',
        flagUrl: 'https://liquipedia.net/commons/images/8/81/Ma_hd.png',
        summonerName: 'Akashi',
        role: 'mid',
      },
      {
        name: 'Fares Saidana',
        nationality: 'Tunisia',
        flagUrl: 'https://liquipedia.net/commons/images/3/31/Tn_hd.png',
        summonerName: 'Xicor',
        role: 'bot',
      },
      {
        name: 'Luca Santos',
        nationality: 'Switzerland',
        flagUrl: 'https://liquipedia.net/commons/images/1/1c/Ch_hd.png',
        summonerName: 'Lucky',
        role: 'support',
      },
    ],
  },
  {
    teamName: 'RAAD',
    slug: 'raad',
    players: [
      {
        name: 'Maged Marwan',
        nationality: 'Egypt',
        flagUrl: 'https://liquipedia.net/commons/images/d/d0/Eg_hd.png',
        summonerName: 'Maged',
        role: 'top',
      },
      {
        name: 'Andreas Aarlund',
        nationality: 'Denmark',
        flagUrl: 'https://liquipedia.net/commons/images/7/7d/Dk_hd.png',
        summonerName: 'Skude',
        role: 'jungle',
      },
      {
        name: 'Oussama Cherradi',
        nationality: 'Morocco',
        flagUrl: 'https://liquipedia.net/commons/images/8/81/Ma_hd.png',
        summonerName: 'Akashi',
        role: 'mid',
      },
      {
        name: 'Fares Saidana',
        nationality: 'Tunisia',
        flagUrl: 'https://liquipedia.net/commons/images/3/31/Tn_hd.png',
        summonerName: 'Xicor',
        role: 'bot',
      },
      {
        name: 'Luca Santos',
        nationality: 'Switzerland',
        flagUrl: 'https://liquipedia.net/commons/images/1/1c/Ch_hd.png',
        summonerName: 'Lucky',
        role: 'support',
      },
    ],
  },
  {
    teamName: '3BL Esports',
    slug: 'ebl-esports',
    players: [
      {
        name: 'Thodoris Bakogiannis',
        nationality: 'Greece',
        flagUrl: 'https://liquipedia.net/commons/images/1/1a/Gr_hd.png',
        summonerName: 'Bako',
        role: 'top',
      },
      {
        name: 'Philippe Le',
        nationality: 'France',
        flagUrl: 'https://liquipedia.net/commons/images/4/40/Fr_hd.png',
        summonerName: 'Akabane',
        role: 'jungle',
      },
      {
        name: 'Hamza Ashraif',
        nationality: 'Egypt',
        flagUrl: 'https://liquipedia.net/commons/images/d/d0/Eg_hd.png',
        summonerName: 'Meza',
        role: 'mid',
      },
      {
        name: 'Nawaf Al Jauid',
        nationality: 'Saudi Arabia',
        flagUrl: 'https://liquipedia.net/commons/images/d/d6/Sa_hd.png',
        summonerName: 'Nawaf',
        role: 'bot',
      },
      {
        name: 'Abdulkader Halwani',
        nationality: 'Egypt',
        flagUrl: 'https://liquipedia.net/commons/images/d/d0/Eg_hd.png',
        summonerName: 'Butcher',
        role: 'support',
      },
    ],
  },
  {
    teamName: 'Anubis Gaming',
    slug: 'anubis-gaming',
    players: [
      {
        name: 'Bariş Karatop',
        nationality: 'Turkey',
        flagUrl: 'https://liquipedia.net/commons/images/4/4b/Tr_hd.png',
        summonerName: 'Juuzou',
        role: 'top',
      },
      {
        name: 'Taha Yurdagüven',
        nationality: 'Turkey',
        flagUrl: 'https://liquipedia.net/commons/images/4/4b/Tr_hd.png',
        summonerName: 'Elramir',
        role: 'jungle',
      },
      {
        name: 'Walid Osman',
        nationality: 'Lebanon',
        flagUrl: 'https://liquipedia.net/commons/images/d/de/Lb_hd.png',
        summonerName: 'Cipher',
        role: 'mid',
      },
      {
        name: 'Eslam Ashraf',
        nationality: 'Egypt',
        flagUrl: 'https://liquipedia.net/commons/images/d/d0/Eg_hd.png',
        summonerName: 'San',
        role: 'bot',
      },
      {
        name: 'Mishal Albarrak',
        nationality: 'Saudi Arabia',
        flagUrl: 'https://liquipedia.net/commons/images/d/d6/Sa_hd.png',
        summonerName: 'Mishal',
        role: 'support',
      },
    ],
  },
];
